# Generated by Django 5.2.7 on 2025-11-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='exp_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='exp_timee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
