# Generated by Django 5.2.7 on 2025-11-05 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_customuser_address_customuser_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
