# Generated by Django 5.2.7 on 2025-11-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
