# Generated by Django 5.2.7 on 2025-11-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0003_mycart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycart',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
