# Generated by Django 5.2.7 on 2025-11-17 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paintapp', '0005_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
